#!/bin/bash
PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

for CHANGE in $( cat "$PROJ_DIR/exported_symbols${1}.txt" ); do
  if [[ ${CHANGE:0:1} == "_" ]] ; then
    NEW="_Ta${1}${CHANGE:3}"
  else
    NEW="Ta${1}${CHANGE:2}"
  fi
  for FILE in $(find "$PROJ_DIR/ast${1}" -type f -name "*.h" -or -name "*.c" -or -name "*.gram"); do
    sed -i "s/$CHANGE/$NEW/" $FILE
  done
  sed -i "s/$CHANGE/$NEW/" ast3/Tools/peg_generator/pegen/c_generator.py
done

sed -i "s/_PyPegen_/_Ta3Pegen_/" ast3/Tools/peg_generator/pegen/c_generator.py
sed -i 's/_PyPegen/_Ta3Pegen/' ast3/Grammar/python.gram

echo "Symbols updated.  Remember to also update autogeneration code like Parser/asdl_c.py."
