#!/bin/bash
PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

for CHANGE in $( cat "$PROJ_DIR/exported_symbols${1}.txt" ); do
  if [[ ${CHANGE:0:1} == "_" ]] ; then
    NEW="_Ta${1}${CHANGE:3}"
  else
    NEW="Ta${1}${CHANGE:2}"
  fi
  find "$PROJ_DIR/ast${1}" -type f -name '*.h' -or -name '*.c' | xargs -n 1 sed -i '' "s/$CHANGE/$NEW/"
done

echo "Symbols updated.  Remember to also update autogeneration code like Parser/asdl_c.py."
